"""IConfigProvider: business-level API consumers depend on (typed DTOs).

IConfigRepository: internal transport-level raw-dict fetch, composed by CacheAsideConfigProvider.
"""

from __future__ import annotations

from typing import Any, Protocol

from .models import Agent, CallFlow, Prompt, ProviderConfig, RuntimeConfig, Tenant, ToolSpec


class IConfigProvider(Protocol):
    async def get_runtime_config(self, tenant_slug: str, agent_slug: str) -> RuntimeConfig | None: ...

    async def get_tenant(self, tenant_slug: str) -> Tenant | None: ...

    async def get_agent(self, tenant_slug: str, agent_slug: str) -> Agent | None: ...

    async def get_provider_config(self, provider_id: str) -> ProviderConfig | None: ...

    async def get_prompt(self, tenant_slug: str, agent_slug: str) -> Prompt | None: ...

    async def get_voice(self, tenant_slug: str, agent_slug: str) -> str | None: ...

    async def get_tools(self, tenant_slug: str, agent_slug: str) -> list[ToolSpec]: ...

    async def get_call_flow(self, tenant_slug: str, call_flow_id: str) -> CallFlow | None: ...

    async def close(self) -> None: ...


class IConfigRepository(Protocol):
    """Raw dicts only; mapping to typed models is CacheAsideConfigProvider's job."""

    async def fetch_tenant(self, tenant_slug: str) -> dict[str, Any] | None: ...

    async def fetch_agent(self, tenant_slug: str, agent_slug: str) -> dict[str, Any] | None: ...

    async def fetch_provider_config(self, provider_id: str) -> dict[str, Any] | None: ...

    async def fetch_call_flow(self, tenant_slug: str, call_flow_id: str) -> dict[str, Any] | None: ...

    async def close(self) -> None: ...
